spring:
  application:
    name: taskify-space

  profiles:
    active: ${APP_PROFILE:development}

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:seugmail@gmail.com}
    password: ${EMAIL_PASSWORD:sua-senha-de-app-no-gmail}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  email:
    root: ${EMAIL_ROOT}
    password-recover:
      uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/new-password/}
      token:
        minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30000000}
  password:
    root: ${PASSWORD_ROOT}
  jwt:
    secret: ${JWT_SECRET:seu-secret-jwt}
    ttl:
      token:
        access: ${TTL_ACCESS_TOKEN:900000}
        refresh: ${TTL_REFRESH_TOKEN:604800000}