spring:
  application:
    name: taskify-space

  profiles:
    active: ${APP_PROFILE:production}

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:seugmail@gmail.com}
    password: ${EMAIL_PASSWORD:sua-senha-de-app-no-gmail}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  email:
    root: ${EMAIL_ROOT}
    password-recover:
      uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/new-password/}
      token:
        minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:10}
      reset-session:
        minutes: ${PASSWORD_RECOVER_RESET_SESSION_MINUTES:10}
    registration-confirmation:
      uri: ${REGISTRATION_CONFIRMATION_URI:http://localhost:5173/confirm-registration?token=}
      token:
        minutes: ${REGISTRATION_CONFIRMATION_TOKEN_MINUTES:5}
      cleanup:
        enabled: ${REGISTRATION_CONFIRMATION_CLEANUP_ENABLED:false}
        fixed-delay: ${REGISTRATION_CONFIRMATION_CLEANUP_FIXED_DELAY:60000}
        batch-size: ${REGISTRATION_CONFIRMATION_CLEANUP_BATCH_SIZE:100}
  password:
    root: ${PASSWORD_ROOT}
  jwt:
    secret: ${JWT_SECRET}
    ttl:
      token:
        access: ${TTL_ACCESS_TOKEN:900000}
        refresh: ${TTL_REFRESH_TOKEN:604800000}

logging:
  charset:
    console: UTF-8
    file: UTF-8

cors:
  origins: ${CORS_ORIGINS:}
