ALTER TABLE refresh_tokens
    ALTER COLUMN issued_at TYPE TIMESTAMP WITH TIME ZONE USING issued_at AT TIME ZONE 'UTC',
    ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE USING expires_at AT TIME ZONE 'UTC',
    ALTER COLUMN revoked_at TYPE TIMESTAMP WITH TIME ZONE USING revoked_at AT TIME ZONE 'UTC';
